from rsf.proj import *

for x in range(25, 25525, 500):
    comando='''./sembl janela=5'''
    filein="./cigcont{0}".format(x)+".rsf"
    fileout="stk{0}".format(x)
    pickout="pick{0}".format(x)
    print pickout
    Flow(fileout,filein,comando)
    Flow(pickout,fileout,'''ipick color=j''')

End()
