from rsf.proj import *

filein='data_psdmvel2000.su'
fileout='dadoMig2000.rsf'

Flow(fileout,filein,'''segyread tape=${SOURCES[0]} su=y endian=n verb=y suxdr=y| put n1=1001 n2=517 n3=50 o1=0 o2=0 o3=50 d1=3 d2=50 d3=100 label1="Depth" unit1="m"''',stdin=0)

for x in range(25, 25525, 500):
    min2=x
    max2=x
    janela='''window min1=0 max1=3000| window min2=%d max2=%d '''%(min2,max2)
    filein="cig"+str(x)
#"cig{0}".format(x)
    Flow(filein,'dadoMig2000.rsf',janela)
    fileout="cigcont"+str(x)
#"cigcont{0}".format(x)
    comando='''./cigcont vi=1400 vr=2000 vf=4000 dv=1 nsp=10''' 
    Flow(fileout,filein,comando)

#window min1=0 max1=3000| window min2=7550 max2=7550 ''',stdin=0)

#Flow('dadoCont.rsf','dadoMig2000.rsf', '''./cigcont 
#    vi=1400 vr=2000 vf=4000 dv=1 nsp=10 ''')


End()
